name: Documentation Update
description: Suggest improvements to documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Please provide details below.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs updating?
      options:
        - README
        - Contributing Guide
        - Code Comments
        - API Documentation
        - Installation Guide
        - Tutorial/Guide
        - Other
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: Describe what currently exists (if anything)
      placeholder: The current docs say...

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Improvement
      description: Describe what should be changed or added
      placeholder: It should instead say...
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason for Change
      description: Why is this change needed?
      placeholder: This is needed because...
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to make this documentation update?
      options:
        - label: I would like to update this documentation myself

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the documentation update
