name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for the idea! Please explain the use-case and proposed solution.
    - type: input
      id: summary
      attributes:
          label: Summary
          placeholder: Add support for ...
      validations:
          required: true
    - type: textarea
      id: problem
      attributes:
          label: Problem to solve
          description: What is the user need or pain point?
      validations:
          required: true
    - type: textarea
      id: proposal
      attributes:
          label: Proposed solution
          description: Describe the change and UX impact.
      validations:
          required: true
    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives considered
    - type: textarea
      id: additional
      attributes:
          label: Additional context
